# Generated by Django 3.0.4 on 2021-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_email', models.EmailField(max_length=100)),
                ('t_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
