# Generated by Django 3.0.4 on 2021-07-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, choices=[('bca', 'BCA'), ('bba', 'BBA'), ('mba', 'MBA'), ('mca', 'MCA')], default='BCA', max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_1', models.IntegerField(default=0)),
                ('marks_2', models.IntegerField(default=0)),
                ('marks_3', models.IntegerField(default=0)),
                ('marks_4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default='1998-01-01')),
                ('roll', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_1', models.CharField(max_length=50)),
                ('sub_2', models.CharField(max_length=50)),
                ('sub_3', models.CharField(max_length=50)),
                ('sub_4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Mark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject')),
            ],
        ),
    ]
