# Generated by Django 3.0.4 on 2021-07-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('jan', 'JANUARY'), ('feb', 'FEBUARY'), ('mar', 'MARCH'), ('apr', 'APRIL'), ('may', 'MAY'), ('jun', 'JUNE'), ('jul', 'JULY'), ('aug', 'AUGUST'), ('sept', 'SEPTEMBER'), ('oct', 'OCTOBER'), ('nov', 'NOVEMBER'), ('dec', 'DECEMBER')], max_length=20)),
                ('attend_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='attendence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Attendece'),
        ),
    ]
