# Generated by Django 3.0.4 on 2021-07-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210722_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Attendece'),
        ),
    ]
