# Generated by Django 3.0.4 on 2021-07-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210722_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendece',
            new_name='Attendence',
        ),
    ]
