# Generated by Django 3.0.4 on 2021-07-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_attendence_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='attendence',
        ),
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Attendence'),
        ),
    ]
