# Generated by Django 3.0.4 on 2021-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210722_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
