# Generated by Django 3.0.4 on 2021-07-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210722_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
    ]
