# Generated by Django 3.0.4 on 2021-07-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_attendence_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='semester',
        ),
    ]
