# Generated by Django 3.0.4 on 2021-07-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentinfo_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence',
        ),
    ]
