# Generated by Django 3.0.4 on 2021-07-24 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210724_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
